In [12]:
import pandas as pd

In [13]:
data = pd.read_csv("C:/Users/mahem/OneDrive/Desktop/Depi/Technical/products.csv")
df = pd.DataFrame(data)
df.head()

   Product_ID Product_Name     Category    Price  Stock  Rating
0         101       Laptop  Electronics  25000.0   15.0     4.6
1         102        Phone  Electronics  18000.0   30.0     4.3
2         103       Tablet  Electronics      NaN   20.0     4.7
3         104      Monitor  Electronics   8500.0    NaN     4.1
4         105     Keyboard  Accessories   1200.0   50.0     3.9

In [14]:
df.describe()

       Product_ID         Price       Stock     Rating
count   16.000000     14.000000   15.000000  16.000000
mean   108.437500   6346.428571   35.133333   4.275000
std      4.661455   7041.974818   26.875019   0.356838
min    101.000000    300.000000   10.000000   3.600000
25%    104.750000   1675.000000   16.500000   4.075000
50%    108.500000   4500.000000   25.000000   4.250000
75%    112.250000   7250.000000   45.000000   4.600000
max    115.000000  25000.000000  100.000000   4.800000

In [15]:
df.dtypes

Product_ID        int64
Product_Name     object
Category         object
Price           float64
Stock           float64
Rating          float64
dtype: object

In [16]:
df1 = df[(df['Price'] > 5000) | (df['Rating'] > 4.5)]
df1

    Product_ID  Product_Name     Category    Price  Stock  Rating
0          101        Laptop  Electronics  25000.0   15.0     4.6
1          102         Phone  Electronics  18000.0   30.0     4.3
2          103        Tablet  Electronics      NaN   20.0     4.7
3          104       Monitor  Electronics   8500.0    NaN     4.1
6          107       Printer       Office   5500.0   12.0     3.6
7          108       Headset  Accessories      NaN   35.0     4.8
10         111    Smartwatch  Electronics   7500.0   18.0     4.6
12         113  External SSD      Storage   6500.0   22.0     4.7

In [18]:
df = df.sort_values('Price', ascending=False)
df

    Product_ID  Product_Name     Category    Price  Stock  Rating
0          101        Laptop  Electronics  25000.0   15.0     4.6
1          102         Phone  Electronics  18000.0   30.0     4.3
3          104       Monitor  Electronics   8500.0    NaN     4.1
10         111    Smartwatch  Electronics   7500.0   18.0     4.6
12         113  External SSD      Storage   6500.0   22.0     4.7
6          107       Printer       Office   5500.0   12.0     3.6
14         115  Office Chair    Furniture   4500.0   10.0     4.1
15         115  Office Chair    Furniture   4500.0   10.0     4.1
9          110       Speaker  Electronics   3000.0   40.0     4.0
8          109        Webcam  Accessories   2200.0   25.0     4.5
13         114    Power Bank  Accessories   1500.0   60.0     4.2
4          105      Keyboard  Accessories   1200.0   50.0     3.9
5          106         Mouse  Accessories    650.0   80.0     4.4
11         112     USB Cable  Accessories    300.0  100.0     3.8
2          103        Tablet  Electronics      NaN   20.0     4.7
7          108       Headset  Accessories      NaN   35.0     4.8

In [21]:
df.isna().sum()

Product_ID      0
Product_Name    0
Category        0
Price           2
Stock           1
Rating          0
dtype: int64

In [31]:
df.fillna(df['Price'].mean(), inplace=True)
df.fillna(df['Stock'].mean(), inplace=True)

In [35]:
df['In_stock'] = df['Stock'].apply(lambda x: 'True' if x > 0 else 'False')
df['Total_value'] = df['Price'] * df['Stock']

In [71]:
df2 = df[(df["Price"] > 3000) & (df["Rating"] >= 4.0)]
df2

,Product_ID,Name,Category,Price,Stock,Rating,In_stock,Total_value,Price_Category
0,101,Laptop,Electronics,25000.000000,15.000000,4.6,True,3.750000e+05,Expensive
1,102,Phone,Electronics,18000.000000,30.000000,4.3,True,5.400000e+05,Expensive
3,104,Monitor,Electronics,8500.000000,6346.428571,4.1,True,5.394464e+07,Medium
10,111,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,1.350000e+05,Medium
12,113,External SSD,Storage,6500.000000,22.000000,4.7,True,1.430000e+05,Medium
14,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
2,103,Tablet,Electronics,6346.428571,20.000000,4.7,True,1.269286e+05,Medium
7,108,Headset,Accessories,6346.428571,35.000000,4.8,True,2.221250e+05,Medium

In [49]:
df['Stock'].mean()
df['Stock'].min()
df['Stock'].max()
df['Stock'].sum()

np.float64(6506.428571428572)

In [51]:
df['Price_Category']= df['Price'].apply(lambda x: 'Expensive' if x > 10000 else ('Medium' if x >= 3000 else 'Cheap'))
df

,Product_ID,Product_Name,Category,Price,Stock,Rating,In_stock,Total_value,Price_Category
0,101,Laptop,Electronics,25000.000000,15.000000,4.6,True,3.750000e+05,Expensive
1,102,Phone,Electronics,18000.000000,30.000000,4.3,True,5.400000e+05,Expensive
3,104,Monitor,Electronics,8500.000000,6346.428571,4.1,True,5.394464e+07,Medium
10,111,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,1.350000e+05,Medium
12,113,External SSD,Storage,6500.000000,22.000000,4.7,True,1.430000e+05,Medium
14,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
15,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
2,103,Tablet,Electronics,6346.428571,20.000000,4.7,True,1.269286e+05,Medium
7,108,Headset,Accessories,6346.428571,35.000000,4.8,True,2.221250e+05,Medium

In [58]:
df.rename(columns={'Product_Name': 'Name'}, inplace=True)
df

,Product_ID,Name,Category,Price,Stock,Rating,In_stock,Total_value,Price_Category
0,101,Laptop,Electronics,25000.000000,15.000000,4.6,True,3.750000e+05,Expensive
1,102,Phone,Electronics,18000.000000,30.000000,4.3,True,5.400000e+05,Expensive
3,104,Monitor,Electronics,8500.000000,6346.428571,4.1,True,5.394464e+07,Medium
10,111,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,1.350000e+05,Medium
12,113,External SSD,Storage,6500.000000,22.000000,4.7,True,1.430000e+05,Medium
14,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
15,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
2,103,Tablet,Electronics,6346.428571,20.000000,4.7,True,1.269286e+05,Medium
7,108,Headset,Accessories,6346.428571,35.000000,4.8,True,2.221250e+05,Medium

In [60]:
df.drop(['Product_ID'], axis=1)

,Name,Category,Price,Stock,Rating,In_stock,Total_value,Price_Category
0,Laptop,Electronics,25000.000000,15.000000,4.6,True,3.750000e+05,Expensive
1,Phone,Electronics,18000.000000,30.000000,4.3,True,5.400000e+05,Expensive
3,Monitor,Electronics,8500.000000,6346.428571,4.1,True,5.394464e+07,Medium
10,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,1.350000e+05,Medium
12,External SSD,Storage,6500.000000,22.000000,4.7,True,1.430000e+05,Medium
14,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
15,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium
2,Tablet,Electronics,6346.428571,20.000000,4.7,True,1.269286e+05,Medium
7,Headset,Accessories,6346.428571,35.000000,4.8,True,2.221250e+05,Medium

In [66]:
df.duplicated().sum()
df.drop_duplicates

<bound method DataFrame.drop_duplicates of     Product_ID          Name     Category         Price        Stock  Rating  \
0          101        Laptop  Electronics  25000.000000    15.000000     4.6
1          102         Phone  Electronics  18000.000000    30.000000     4.3
3          104       Monitor  Electronics   8500.000000  6346.428571     4.1
10         111    Smartwatch  Electronics   7500.000000    18.000000     4.6
12         113  External SSD      Storage   6500.000000    22.000000     4.7
14         115  Office Chair    Furniture   4500.000000    10.000000     4.1
2          103        Tablet  Electronics   6346.428571    20.000000     4.7
7          108       Headset  Accessories   6346.428571    35.000000     4.8

   In_stock   Total_value Price_Category
0      True  3.750000e+05      Expensive
1      True  5.400000e+05      Expensive
3      True  5.394464e+07         Medium
10     True  1.350000e+05         Medium
12     True  1.430000e+05         Medium
14     True  4.500000e+04         Medium
2      True  1.269286e+05         Medium
7      True  2.221250e+05         Medium  >

In [67]:
df.sort_values('Rating', ascending=False)

,Product_ID,Name,Category,Price,Stock,Rating,In_stock,Total_value,Price_Category
7,108,Headset,Accessories,6346.428571,35.000000,4.8,True,2.221250e+05,Medium
12,113,External SSD,Storage,6500.000000,22.000000,4.7,True,1.430000e+05,Medium
2,103,Tablet,Electronics,6346.428571,20.000000,4.7,True,1.269286e+05,Medium
0,101,Laptop,Electronics,25000.000000,15.000000,4.6,True,3.750000e+05,Expensive
10,111,Smartwatch,Electronics,7500.000000,18.000000,4.6,True,1.350000e+05,Medium
1,102,Phone,Electronics,18000.000000,30.000000,4.3,True,5.400000e+05,Expensive
3,104,Monitor,Electronics,8500.000000,6346.428571,4.1,True,5.394464e+07,Medium
14,115,Office Chair,Furniture,4500.000000,10.000000,4.1,True,4.500000e+04,Medium

In [68]:
df.to_csv('products_modified.csv', index=False)